{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[[]]},"sections":[],"metadata":{"externalID":"CameraManagerFrameWork","symbolKind":"module","modules":[{"name":"CameraManagerFrameWork"}],"title":"CameraManagerFrameWork","role":"collection","roleHeading":"Framework"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/cameramanagerframework"]},{"paths":["\/documentation\/cameramanagerframework"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraManager","doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraMetalView","doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/MultiCameraView"],"generated":true,"anchor":"Classes"},{"identifiers":["doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraManagerFrameWorkDelegate"],"generated":true,"anchor":"Protocols","title":"Protocols"},{"title":"Structures","anchor":"Structures","identifiers":["doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraOptions"],"generated":true},{"generated":true,"title":"Enumerations","anchor":"Enumerations","identifiers":["doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraRenderingMode","doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraScreenMode","doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraSessionMode"]}],"references":{"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork":{"title":"CameraManagerFrameWork","kind":"symbol","abstract":[],"url":"\/documentation\/cameramanagerframework","type":"topic","identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork","role":"collection"},"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork/MultiCameraView":{"abstract":[],"type":"topic","role":"symbol","title":"MultiCameraView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiCameraView","kind":"identifier"}],"navigatorTitle":[{"text":"MultiCameraView","kind":"identifier"}],"url":"\/documentation\/cameramanagerframework\/multicameraview","identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/MultiCameraView"},"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork/CameraOptions":{"role":"symbol","title":"CameraOptions","type":"topic","url":"\/documentation\/cameramanagerframework\/cameraoptions","identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraOptions","abstract":[{"type":"text","text":"CameraOptions For CameraManager"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CameraOptions"}],"kind":"symbol"},"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork/CameraManager":{"url":"\/documentation\/cameramanagerframework\/cameramanager","type":"topic","abstract":[{"text":"Main Class For CameraManager","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraManager"}],"identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraManager","title":"CameraManager","navigatorTitle":[{"kind":"identifier","text":"CameraManager"}]},"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork/CameraMetalView":{"kind":"symbol","url":"\/documentation\/cameramanagerframework\/camerametalview","type":"topic","abstract":[],"role":"symbol","title":"CameraMetalView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CameraMetalView","kind":"identifier"}],"identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraMetalView","navigatorTitle":[{"kind":"identifier","text":"CameraMetalView"}]},"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork/CameraScreenMode":{"url":"\/documentation\/cameramanagerframework\/camerascreenmode","kind":"symbol","role":"symbol","identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraScreenMode","abstract":[{"type":"text","text":"Modes for Camera Screen"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraScreenMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CameraScreenMode"}],"title":"CameraScreenMode"},"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork/CameraSessionMode":{"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraSessionMode","kind":"identifier"}],"url":"\/documentation\/cameramanagerframework\/camerasessionmode","identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraSessionMode","title":"CameraSessionMode","navigatorTitle":[{"text":"CameraSessionMode","kind":"identifier"}],"type":"topic","abstract":[{"text":"Modes For Camera Session","type":"text"}]},"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork/CameraManagerFrameWorkDelegate":{"url":"\/documentation\/cameramanagerframework\/cameramanagerframeworkdelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CameraManagerFrameWorkDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"CameraManagerFrameWorkDelegate"}],"identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraManagerFrameWorkDelegate","navigatorTitle":[{"text":"CameraManagerFrameWorkDelegate","kind":"identifier"}],"kind":"symbol","title":"CameraManagerFrameWorkDelegate"},"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork/CameraManagerFrameWorkVersionString":{"type":"topic","fragments":[{"text":"CameraManagerFrameWorkVersionString","kind":"identifier"}],"title":"CameraManagerFrameWorkVersionString","url":"\/documentation\/cameramanagerframework\/cameramanagerframeworkversionstring","role":"symbol","identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraManagerFrameWorkVersionString","abstract":[{"type":"text","text":"Project version string for CameraManagerFrameWork."}],"kind":"symbol"},"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork/CameraRenderingMode":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraRenderingMode"}],"url":"\/documentation\/cameramanagerframework\/camerarenderingmode","identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraRenderingMode","title":"CameraRenderingMode","abstract":[{"text":"Modes for rendering the camera output.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CameraRenderingMode"}]},"doc://cc.otis.cameraMananger.CameraManagerFrameWork/documentation/CameraManagerFrameWork/CameraManagerFrameWorkVersionNumber":{"url":"\/documentation\/cameramanagerframework\/cameramanagerframeworkversionnumber","abstract":[{"type":"text","text":"Project version number for CameraManagerFrameWork."}],"role":"symbol","kind":"symbol","title":"CameraManagerFrameWorkVersionNumber","identifier":"doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraManagerFrameWorkVersionNumber","type":"topic","fragments":[{"text":"CameraManagerFrameWorkVersionNumber","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraManagerFrameWorkVersionNumber","doc:\/\/cc.otis.cameraMananger.CameraManagerFrameWork\/documentation\/CameraManagerFrameWork\/CameraManagerFrameWorkVersionString"],"anchor":"Variables","generated":true,"title":"Variables"}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}